export enum SCREENS {
  AUTH_HOME = 'AUTH_HOME',
  AUTH_ACCOUNT_EMAIL = 'AUTH_ACCOUNT_EMAIL',
  AUTH_NEW_ACCOUNT = 'AUTH_NEW_ACCOUNT',
  /* PLOP_INJECT_SCREEN */
  AUTH_ACCOUNT_VERIFIED = 'AUTH_ACCOUNT_VERIFIED',
}
