name: Android QA Build

on:
  workflow_dispatch:
  release:
    types: [published]
  pull_request:
    branches: [main, develop]

jobs:
  android-build:
    name: Android Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up our JDK environment
        uses: actions/setup-java@v3.3.0
        with:
          java-version: '11'
          distribution: 'zulu'
  
      - name: Install packages
        uses: ./.github/actions/node-env

      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-
      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew

      - name: Build Android App Bundle
        run: |
          cd android && ./gradlew assembleRelease --no-daemon
          
        ## sign generate apk using github secrets
#       - name: Sign App Bundle
#         id: sign_app
#         uses: r0adkll/sign-android-release@v1
#         with:
#           releaseDirectory: android/app/build/outputs/apk/release
#           signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
#           alias: ${{ secrets.ANDROID_ALIAS }}
#           keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
#           keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

      ## upload artifact to action
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Gakko App Bundle
          path: ${{steps.sign_app.outputs.signedReleaseFile}}

#       ## Distribute app to Firebase App Distribution for testing / use google play internal track if you have a google play account
#       - name: upload artifact to Firebase App Distribution
#         uses: wzieba/Firebase-Distribution-Github-Action@v1
#         with:
#           appId: ${{secrets.ANDROID_FIREBASE_APP_ID}}
#           token: ${{secrets.ANDROID_FIREBASE_TOKEN}}
#           groups: testers
#           file: ${{steps.sign_app.outputs.signedReleaseFile}}

      ## upload abb to google play  using https://github.com/r0adkll/upload-google-play
