name: CI
on: 
  push:
  pull_request:

jobs:
  build:
    name: Build CI
    runs-on: ubuntu-latest
    steps:

      - name: Checkout and install packages
        # Directory name only
        uses: actions/node-env@hmarques09-ci
        
#       - name: Run linter
#         run: yarn lint
        
#       - name: Run Tests
#         run: yarn test
