name: CI
on: 
  workflow_call:
  push: 
    branches: [main, develop]

jobs:
  build:
    name: Setup Node, Install packages, Run Eslint, and Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the commit
        uses: actions/checkout@v3
      - name: Install packages
        uses: ./.github/actions/node-env
        
      - name: Run Eslint
        run: yarn lint
        
      - name: Run ci tests & publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: 50bae8c690f8779f7a13a33326adef1dad122fd316540a799fc4507d3b4285fb
        with:
          coverageCommand: yarn test:ci
          debug: true
