name: CI
on: 
  push:
  pull_request:

jobs:
  build:
    name: Build CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node and Install packages
        # Directory name only
        uses: ./.github/actions/node-env
        
#       - name: Run linter
#         run: yarn lint
        
#       - name: Run Tests
#         run: yarn test
