name: CI
on: 
  push:
  pull_request:
  workflow_call:

jobs:
  build:
    name: Build CI
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: ./.github/workflows/ci.yml
        
#       - name: Run linter
#         run: yarn lint
        
#       - name: Run Tests
#         run: yarn test
