name: CI
on: 
  push:
  pull_request:

jobs:
  build:
    name: Build CI
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/node-env
        
      - name: Run linter
        run: yarn lint
        
      - name: Run Tests
        run: yarn test
