name: CI
on: 
  push:
  pull_request:

jobs:
  build:
    name: Build CI
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        
      - name: Build
        uses: ./.github/actions/node-env.yml
        
#       - name: Run linter
#         run: yarn lint
        
#       - name: Run Tests
#         run: yarn test
